# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yherda < Formula
  desc "Command line interface for Yherda"
  homepage "https://github.com/yherda-opensource/yherda-cmd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.0/yherda-cmd_0.1.0_darwin_amd64.tar.gz"
      sha256 "9243ad93ab90711143c3ffad8719f44c33d31e9965bd82ba6128b6b1264b7d95"

      define_method(:install) do
        bin.install "yherda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.0/yherda-cmd_0.1.0_darwin_arm64.tar.gz"
      sha256 "433d3ef117131127a8a71176998a4b46a59b207a8b3754a26df1d35ca2fa5160"

      define_method(:install) do
        bin.install "yherda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.0/yherda-cmd_0.1.0_linux_amd64.tar.gz"
      sha256 "0f3f791d52e3fbc36777ae0ddd2c17521c66c40dcb443fe937c67b8ce32f5e49"
      define_method(:install) do
        bin.install "yherda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.0/yherda-cmd_0.1.0_linux_arm64.tar.gz"
      sha256 "3ac5f40f3242126157595c8c98efc8c9a5388896bfe5368a6a354f98a45dc047"
      define_method(:install) do
        bin.install "yherda"
      end
    end
  end

  test do
    system "#{bin}/yherda", "--version"
  end
end
