# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yherda < Formula
  desc "Command line interface for Yherda"
  homepage "https://github.com/yherda-opensource/yherda-cmd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.1/yherda-cmd_0.1.1_darwin_amd64.tar.gz"
      sha256 "4a63b55a30cd5adf0fdd1417c2e33582e9db0d36533b49e2027f52d72d3f391e"

      define_method(:install) do
        bin.install "yherda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.1/yherda-cmd_0.1.1_darwin_arm64.tar.gz"
      sha256 "823afdc2dafc2f2832cf074fdd421af91b632ddb97d60038c2f84b2aacfcc45b"

      define_method(:install) do
        bin.install "yherda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.1/yherda-cmd_0.1.1_linux_amd64.tar.gz"
      sha256 "3f3b36a1acbb82b9c45ee4fd3b93e3462191d12d2c9791ae3308dd7d3ef0f2aa"
      define_method(:install) do
        bin.install "yherda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yherda-opensource/yherda-cmd/releases/download/v0.1.1/yherda-cmd_0.1.1_linux_arm64.tar.gz"
      sha256 "25ddd01c6f2909e80bc57cb34136a83d25aa5fdc7c12867245a04b272fbe5497"
      define_method(:install) do
        bin.install "yherda"
      end
    end
  end

  test do
    system "#{bin}/yherda", "--version"
  end
end
